dist: bionic
language: node_js
node_js:
  - "12.13.1"

cache:
  directories:
    - ./client/node_modules
    - ./node_modules

before_script:
  - npm install --prefix client
  - npm run front:lint
  - npm install

script:
  - npm run test --prefix client

before_deploy:
  - zip -r deploy_$TRAVIS_BUILD_NUMBER.zip . -x /node_modules* /client*
  - zip -r deploy_$TRAVIS_BUILD_NUMBER.zip /client/build

deploy:
  provider: s3
  access_key_id: $AWS_KEY_ID
  secret_access_key: $AWS_SECRET
  bucket: "fem4"
  upload-dir: travis-builds
  skip_cleanup: true
  region: eu-central-1
  on:
    branch: deploy_test

branches:
  only:
    - master
    - develop
    - deploy_test
# zip -r deploy.zip . -x /node_modules* /client*
# zip -r deploy.zip /client/build
