dist: bionic
language: node_js
node_js:
  - "12.13.1"

cache:
  directories:
    - ./client/node_modules
    - ./node_modules

before_script:
  - npm install --prefix client
  - npm run front:lint:fix
  - npm install

script:
  - npm run test --prefix client

branches:
  only:
    - master
    - develop
